### ISSUE TITLE
Crash when opening the stickers or GIFs panel

### ISSUE THREAD

**Issue by gianmarcogg03** [OwlGramDev/OwlGram#16]
Steps to reproduce
1. Open a chat
2. Open the stickers or GIFs panel

Details
App Version: 2.4.1 (2918)
Base Version: 9.1.3 (2917)
Device: Google Pixel 6a
OS Version: 13
Google Play Services: true
Performance Class: HIGH
Locale: it-IT
Camera: CameraX
Crash Date: 16 nov 2022, 08:09

[Logcat (1).log](https://github.com/OwlGramDev/OwlGram/files/10023787/Logcat.1.log)

https://user-images.githubusercontent.com/28053717/202238001-cf4eb958-e6be-4775-8571-2bd51f359b3d.mp4

#crash

**Comment by tappo03** [comment]
hi, sorry for the late reply, to report a bug we suggest to use the forum
t.me/OwlGramForum - t.me/OwlGramForumIT.
