### ISSUE TITLE
[Feature Request] Option to choose the emoji set

### ISSUE THREAD

**Issue by firezt** [OwlGramDev/OwlGram#17]
Hi.
If possible, I'd like to request an option to be able to select other emoji sets, as it is possible to do in Telegram X, for example.
![a](https://user-images.githubusercontent.com/87192386/205499849-f0c2f756-36e3-405e-bc4c-bc3a0888d96e.jpg)

Thanks for the great app.

**Comment by tappo03** [comment]
Hi, we don't take feature via GitHub, we suggest you to use the group.
t.me/OwlGramForum
