### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by dennis90a** [OwlGramDev/OwlGram#2]

**Comment by brnwlshubh** [comment]
What's the status?

**Comment by tappo03** [comment]
We can't publish it on F-Droid as soon as we don't have a FOSS version, installl OwlGram via:

📦 **Stable Releases**
├ [Google Play Store](https://play.google.com/store/apps/details?id=it.owlgram.android)
├ [App Center](https://install.appcenter.ms/users/owlgram/apps/owlgram/distribution_groups/public)
├ [APKs Channel](https://t.me/OwlGramAPKs)
├ [GitHub](https://github.com/OwlGramDev/OwlGram/releases/tag/%23stable)
└ [OwlGram Website](https://files.owlgram.org/OwlGram.apk)

👨‍🔬**Beta Releases**
├ [Google Play Store](https://play.google.com/store/apps/testing/it.owlgram.android)
├ [App Center](https://install.appcenter.ms/users/owlgram/apps/owlgram-beta/distribution_groups/public-beta)
├ [APKs Channel](https://t.me/OwlGramBeta)
├ [GitHub](https://github.com/OwlGramDev/OwlGram/releases/tag/%23beta)
└ [OwlGram Website](https://files.owlgram.org/universal-beta.apk)

🔗 [OwlGram Network Channel](https://t.me/OwlGramNetwork)

**Comment by comradekingu** [comment]
@tappo03 Does it meet https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo ?

**Comment by tappo03** [comment]
> @tappo03 Does it meet https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo ?

Already asked, we can't due Google libraries

**Comment by machiav3lli** [comment]
I guess it should be possible to create a FOSS build variant inspired by Telegram FOSS's work

**Comment by tappo03** [comment]
> I guess it should be possible to create a FOSS build variant inspired by Telegram FOSS's work

We don't have enough time or developers to do it

**Comment by machiav3lli** [comment]
It would help if you re-open the issue so interested devs would be aware of this

**Comment by tappo03** [comment]
i'm a part of the developer team and I can say that will not do this.
if an external dev want to do it can create a PR, but our team is strict closed and not accessible to other peoples.
