### ISSUE TITLE
 Update screan glitch 

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [OwlGramDev/OwlGram#5]
![Screenshot_20220413-085541_OwlGram.jpg](https://user-images.githubusercontent.com/92474350/163118144-e989618c-9845-40b3-a46c-da129db1d7e8.jpg)

I was trying ti enable beta, buy once the app tell me ti installo It this appened

**Comment by tappo03** [comment]
already fixed, thanks for reporting it, anyway you can make an issue in Italian or use our group (t.me/OwlGramNetwork)
