### ISSUE TITLE
Translations on Hosted Weblate

### ISSUE THREAD

**Issue by comradekingu** [OwlGramDev/OwlGram#6]
Came to know of OwlGram via https://github.com/WeblateOrg/hosted/issues/344
Hoping to see it added to https://hosted.weblate.org/hosting/ for mutual benefit.
I can help set it up, or you can add "kingu" :)

**Comment by Laky-64** [comment]
We prefer to keep translations.owlgram.org

**Comment by comradekingu** [comment]
Don't really know why.
To me there is no upside to spying scripts and broken functionality.
