### ISSUE TITLE
Top features with commits 

### ISSUE THREAD

**Issue by Gherkashen2** [OwlGramDev/OwlGram#7]
Add experimental ability to set separated passcode for each account:
https://github.com/Forkgram/TelegramAndroid/commit/01d6110d9e9950a7e7783e7d24842743bbe42979

Added ability to select all messages between 2 selections from bar 
https://github.com/exteraSquad/exteraGram/commit/dab4b3a233f0e02ad2c733982708e5787f097fba

Add ".wav" support
https://github.com/exteraSquad/exteraGram/commit/c2586e129c735d134774d414655c308b81d5408e

Add ability to select all messages between 2 selections from bar 
https://github.com/exteraSquad/exteraGram/commit/dab4b3a233f0e02ad2c733982708e5787f097fba

Add ability to seek voice messages from player alert
https://github.com/exteraSquad/exteraGram/commit/1649281e9e30e8fe01fb0e3aa2a0dd2f82f7d3f8

Add "Show message ID"
https://github.com/exteraSquad/exteraGram/commit/0699b26e243d49cb57bc587b6e86649bc17da7b8

Add "Send message before send sticker"
https://github.com/exteraSquad/exteraGram/commit/559ded164494e753598b51d3755aac3b3c5a473a

Add ability to attach text to voice message before sending it
https://github.com/Forkgram/TelegramAndroid/commit/2c4aee06b727fc4371e7ee7a125d88d68ced8b45

Days of week to schedule time picker.
https://github.com/Forkgram/TelegramAndroid/commit/8f42f0c1b75794920d56e4ae353478cc9e9eb8f0

feat: a lot of self-destruct timer's options in secret chats.
Add 2, 3, 4, 5, 10, 15, 20, 30, 40 minutes.
Add 2, 3, 5, 8, 12, 16 hours.Add 2, 3, 7 and 32 days.
https://github.com/Forkgram/TelegramAndroid/commit/30f5d0e3498a2bfe592b70b0e4e0a4b1114c9048

Add auto inserting caption to cloud GIF if EditField has text.
https://github.com/Forkgram/TelegramAndroid/commit/18c603fe5ed4d24c3882dc41e7f876170e3d337a

Add option to disable sending sticker info in photos
https://github.com/Forkgram/TelegramAndroid/commit/a4319f55774893cc9190fb9f175c8ce597d9919d

**Comment by tappo03** [comment]
Hi, to send feature please use us group (t.me/OwlGramChat, you can simple do #feature https://github.com/OwlGramDev/OwlGram/issues/7).
