### ISSUE TITLE
Add "Proxy Settings" on login activity

### ISSUE THREAD

**Issue by Shikopat** [OwlGramDev/OwlGram#8]
https://github.com/exteraSquad/exteraGram/commit/6e54aadb6271b19f9cd4dcf6cc664039dc745a2f

WE NEED THIS ESSENTIAL FEATURE

**Comment by Attorelle** [comment]
:thinking:

**Comment by tappo03** [comment]
Added in [OwlGram 1.9.0 Beta 2](https://github.com/OwlGramDev/OwlGram/releases/tag/%23beta)
