### ISSUE TITLE
Multiple spoilers in a single message are treated as a single spoiler

### ISSUE THREAD

**Issue by Focshole** [OwlGramDev/OwlGram#9]
If in a message you have multiple separated spoilers, once you tap on one of those, it shows all of them instead of the only one you tapped on.

**Comment by Laky-64** [comment]
This is a telegram android issue, not OwlGram issue

**Comment by hey-adithya** [comment]
![IMG_20220526_071146_988](https://user-images.githubusercontent.com/80088944/170397904-5f819119-1f02-4dd2-8dab-b471ff24f52c.jpg)
**Notification not show message**

**Comment by Laky-64** [comment]
Just disable passcode
